### ISSUE TITLE
Fix: Footer

### ISSUE THREAD

**Issue by InvisibleSpectator** [Anastasiya-s/culture-portal#29]
На главной странице футер висит в воздухе

**Comment by InvisibleSpectator** [comment]
Если контента много, то фиксированный футер его перекроет при прокрутке до конца.
![image](https://user-images.githubusercontent.com/33596224/75365511-ba4bd900-58d6-11ea-8399-8f4b3e55e53a.png)

**Comment by AnzhelaMartsinovich** [comment]
@InvisibleSpectator 
Выход из положения простой, высота футера + отступ, который ты хочешь.
<img width="1425" alt="Снимок экрана 2020-02-26 в 7 58 59 ПП" src="https://user-images.githubusercontent.com/51420320/75368286-8cfd2c00-58d2-11ea-8ec4-5fe32c57ccc1.png">

Применила именно такой способ, так как для других, которые я знаю, нужно контент оборачивать в дополнительную обертку и для это обертки задавать отступ. 
Если знаешь способ получше, то поделись, пожалуйста)
